services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: global_contacts
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
  app:
    container_name: app
    environment:
      PORT: 8080
      DB_NAME: global_contacts 
      DB_USER: username 
      DB_HOST: database
      DB_PORT: 5432
      DB_PASSWORD: password 
      DB_DRIVER: postgres
    ports:
      - "8080:8080"
    build: .
    volumes:
      - app_data:/app/data
    depends_on:
      - database

volumes:
  database_data:
  app_data: