services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: global_contacts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: .
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - app_data:/app/data
    command: npm install && echo 'Hiiiiiiiii' && npm run build && npm run start
    depends_on:
      - postgres

volumes:
  postgres_data:
  app_data: